### PR TITLE
[ENH] Test against python 3.10 and python 3.11

### LINKED ISSUE #482: ENH Support and test against python 3.10, 3.11
**Is your feature request related to a problem? Please describe.**
These are newer python versions that most operating systems ship by default. We should test against these.

**Describe the solution you'd like**
Users can install serpent-tools on python 3.10 and 3.11

Our CI tests against these two versions

### PR DESCRIPTION
**Pull request by drewejohnson**
Closes #482 by testing against python 3.10 and python 3.11 in our CI test suite

- [x] PR fits the [project scope](http://serpent-tools.readthedocs.io/en/latest/develop/contributing.html#project-scope)
- [x] Code to be committed is [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and matches the [code style](http://serpent-tools.readthedocs.io/en/latest/develop/codestyle.html#code-style) of the project
- [x] New and/or changed features are [well documented](http://serpent-tools.readthedocs.io/en/latest/develop/documentation.html#documentation) and have adequate testing
- [x] For first-time contributors, you have included your attribution in [`docs/contributors.rst`](https://github.com/CORE-GATECH-GROUP/serpent-tools/blob/develop/docs/contributors.rst)

### CODE REVIEW

**Review by DanKotlyar — APPROVED** [review]

**Comment by DanKotlyar** [comment]
I see there is one failed check. What should I do @drewejohnson ?

**Comment by drewejohnson** [comment]
@DanKotlyar I'm trying to figure out why 3.11 builds are failing. Something about scipy from a pip install I think? I haven't nailed it down just yet. But when I do, I'll let you know

**Comment by drewejohnson** [comment]
I am at a loss as to why we cannot get scipy to install w/ pip for python 3.11 in our builds.

Pip pulls several versions, downgrading to 1.9.0, which is the only one without a wheel `.whl` file. This triggers a full build of scipy, because we get the source distribution w/ the `.tar.gz`, and that fails.

I can confirm the behavior though w/ a fresh conda environment. So maybe we have some weird dependency restrictions?

**Comment by drewejohnson** [comment]
Okay, found the problem. And the problem is me. Restricting `requires-python = ">=3.8,<=3.11"` is too strict of an upper bound, because the upper limit *only* matches python 3.11.*0*

If we bump that up to 3.12 or 3.13, then it builds :facepalm:

**Review by DanKotlyar — APPROVED** [review]

**Pull request merged**
