### PR TITLE
[DEP] Drop python 3.5, 3.6, 3.7; build with pyproject.toml

### LINKED ISSUE #425: Drop support for python 3.5
Python 3.5 has reached it's end of life and will only be receiving security fixes starting end of September 2020 - https://www.python.org/downloads/release/python-3510/

I move that we drop support for python 3.5 in release 0.10.0, whenever that comes out.

It looks like the major linux distributions are at least on python 3.7, [debian and ubuntu at least](https://wiki.debian.org/Python), and MacOS ships with python 3.8.

As for API changes, I don't think we'll be hit with anything surprising. Some niceties we'll pick up will be better / full integration of the pathlib and typing libraries

### LINKED ISSUE #477: ENH Drop support for python 3.7
**Is your feature request related to a problem? Please describe.**
Python 3.7 reaches end of life on 2023-06-27 - https://peps.python.org/pep-0537/

**Describe the solution you'd like**
serpent-tools has a minimum python version of 3.8

**Describe alternatives you've considered**
N/A

**Additional context**
I'm not sure when this should happen. Maybe when critical dependencies like numpy don't support py37?

### LINKED ISSUE #479: ENH Install with pyproject.toml and setup.cfg
**Is your feature request related to a problem? Please describe.**
The use of `setup.py` for installing python packages is falling by the wayside. The current methodology is to use a `pyproject.toml` file, usually with a `setup.cfg` file for `setuptools` specific options

- https://packaging.python.org/en/latest/tutorials/packaging-projects/

I'm partial to sticking with `setuptools` as the build backend, but there are a lot of options

- https://setuptools.pypa.io/en/latest/
- https://hatch.pypa.io/latest/
- https://flit.readthedocs.io/en/latest/
- https://pdm.fming.dev/latest/

**Describe the solution you'd like**

- [ ] All the content from `setup.py` is distributed to an appropriate build file or no more than two build files
- [ ] `pyproject.toml` is built with at least the minimum data on how to select the package builder
- [ ] Building with `pip install .` or similar tooling from local repository
- [ ] Support for editable installs / developmental installs (e.g., `pip install -e `)
-
**Describe alternatives you've considered**

Alternative is to not do anything? But then at some point, because we don't have a `pyproject.toml`, we don't be able to build the package from source

**Additional context**
Links above are very helpful

### PR DESCRIPTION
**Pull request by drewejohnson**
Closes #425 

Also update our CI workflows to
- bump various action versions
- use main branch

Closes #477 and now only py38 and py39 are supported. See #482 for py3.10 and 3.11

Closes #479 as the `pyproject.toml` file is the primary file for controlling the build. Used now in testing and in documentation

Make sure you have read over the developer guide to ease
the review process. These include:

- [x] PR fits the [project scope](http://serpent-tools.readthedocs.io/en/latest/develop/contributing.html#project-scope)
- [x] Code to be committed is [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and matches the [code style](http://serpent-tools.readthedocs.io/en/latest/develop/codestyle.html#code-style) of the project
- [x] New and/or changed features are [well documented](http://serpent-tools.readthedocs.io/en/latest/develop/documentation.html#documentation) and have adequate testing
- [x] For first-time contributors, you have included your attribution in [`docs/contributors.rst`](https://github.com/CORE-GATECH-GROUP/serpent-tools/blob/develop/docs/contributors.rst)

### CODE REVIEW

**Review by DanKotlyar — APPROVED** [review]

**Comment by drewejohnson** [comment]
@DanKotlyar do you see anything wrong with dropping python 3.7 as well? Two packages, numpy and matplotlib, have already dropped support for python 3.7 - #477 

It would be easier to drop 3.7 here, rather than limit numpy and matplotlib versions in this PR, then change the limits again in a follow up PR

**Comment by DanKotlyar** [comment]
@drewejohnson I see no issue in dropping python 3.7

**Review by DanKotlyar — APPROVED** [review]

**Comment by drewejohnson** [comment]
@DanKotlyar I'm not sure why, but the jupyter notebooks don't seem to be working in the test suite as well as I expected. I propose we remove that check from the CI so we can get this (already large) PR merged, and then update CI to re-run the jupyter notebooks

**Comment by DanKotlyar** [comment]
@drewejohnson  I have no objection removing that check. What (and how) should I so?

**Comment by drewejohnson** [comment]
> @drewejohnson I have no objection removing that check. What (and how) should I so?

No worries @DanKotlyar, I removed them in b063705 and will make an issue to re-add them

**Comment by drewejohnson** [comment]
@DanKotlyar ready to roll

**Pull request merged**
